In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
print("Hello")

Hello


In [4]:
import numpy as np
print(np.__version__)

1.26.4


In [10]:
a=np.array([1,2,3,4,5])
print(a.shape)
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b.shape)
c=np.array([[[1,2,3],[

(5,)
(3, 3)


In [20]:
d=np.array([[[1,2,3],[4,5,6]],[[100,200,300],[400,500,600]]])
print(d.shape)

(2, 2, 3)


In [26]:
a=np.array([1,2,3,4])
b=np.array([True,False])
c=np.array([1+2j,2+4j])
for i in [a,b,c]:
    print(i.dtype)

int32
bool
complex128


In [28]:
#Specifying the datatype
a=np.array([1,2,3],dtype=np.float32)
print(a,a.dtype)


[1. 2. 3.] float32


In [32]:
c=[1,2,3]
a=np.array(c)
b=np.asarray(c)
print(a,b)

[1 2 3] [1 2 3]


In [40]:
#ones
a=np.ones((3,3))
b=np.zeros((10,10))
print(a,b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [44]:
#arrange
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [46]:
a=np.arange(2,10,2)
print(a)

[2 4 6 8]


In [48]:
print(np.linspace(1,10,40))

[ 1.          1.23076923  1.46153846  1.69230769  1.92307692  2.15384615
  2.38461538  2.61538462  2.84615385  3.07692308  3.30769231  3.53846154
  3.76923077  4.          4.23076923  4.46153846  4.69230769  4.92307692
  5.15384615  5.38461538  5.61538462  5.84615385  6.07692308  6.30769231
  6.53846154  6.76923077  7.          7.23076923  7.46153846  7.69230769
  7.92307692  8.15384615  8.38461538  8.61538462  8.84615385  9.07692308
  9.30769231  9.53846154  9.76923077 10.        ]


In [54]:
#identity matrix
print(np.eye(3,2))

[[1. 0.]
 [0. 1.]
 [0. 0.]]


In [68]:
print(np.array([1,2,3,4])+np.array([5,6,7,8]))
print(np.array([1,2,3,4])-np.array([5,6,7,8]))
print(np.array([1,2,3,4])*np.array([5,6,7,8]))
print(np.array([1,2,3,4])/np.array([5,6,7,8]))
print(a*2)
print(a/2)
print(np.sqrt(a))
print(np.exp(a))

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[ 4  8 12 16]
[1. 2. 3. 4.]
[1.41421356 2.         2.44948974 2.82842712]
[   7.3890561    54.59815003  403.42879349 2980.95798704]


In [70]:
#BroadCasting
a=np.array([1,2,3])
print(a+2)

[3 4 5]


In [72]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([10,11,12])
print(a+b)

[[11 13 15]
 [14 16 18]]


In [6]:
#slicing and indexing
a=np.array([1,2,3,4])
print(a[0])

1


In [14]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(b[0, 0])  
print(b[2, 1])

1
8


In [20]:
a=np.array([1,2,3,4,5])
b=np.array([0,1,2])
print(a[b])

[1 2 3]


In [22]:
#boolean indexing
a=np.array([1,2,3,4,5])
print(a[a>3])

[4 5]


In [24]:

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(a[2:6])  
print(a[:4])   
print(a[5:])   
print(a[::2])
print(a[::-1]) 


[3 4 5 6]
[1 2 3 4]
[6 7 8 9]
[1 3 5 7 9]
[9 8 7 6 5 4 3 2 1]


In [28]:

b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(b[0:2, 0:2])
print(b[:, 1])      


[[1 2]
 [4 5]]
[2 5 8]


In [32]:
a=np.array([1,2,3,4,5])
print(a[1:3:2])
print(a[::-1])

[2]
[5 4 3 2 1]


In [34]:
a=np.array([1,2,3,4,4])
a[2]=100
print(a)

[  1   2 100   4   4]


In [52]:
a=np.array([1,2,3,4,5,6])
b=a.reshape(3,2)
print(b)
c=a.reshape(2,1,3)
print(c)
print(c.ravel())

[[1 2]
 [3 4]
 [5 6]]
[[[1 2 3]]

 [[4 5 6]]]
[1 2 3 4 5 6]


In [72]:
a=np.array([1,2,3])
b=np.array([5,6,7])
c=np.stack((a,b))
print(c)
print(np.concatenate((a,b),axis=None))


[[1 2 3]
 [5 6 7]]
[1 2 3 5 6 7]


In [74]:
a = np.array([1, 2])
b = np.array([3, 4])

# Stack arrays horizontally
c = np.hstack((a, b))
print(c)

# Stack arrays vertically
d = np.vstack((a, b))
print(d)

# Stack arrays along a new axis
e = np.stack((a, b), axis=1)
print(e)

[1 2 3 4]
[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [76]:
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16]])

# Split the array horizontally into 2 sub-arrays
left, right = np.hsplit(a, 2)
print("Horizontal split:")
print("Left sub-array:\n", left)
print("Right sub-array:\n", right)


Horizontal split:
Left sub-array:
 [[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]
Right sub-array:
 [[ 3  4]
 [ 7  8]
 [11 12]
 [15 16]]


In [80]:
a=np.array([1,2,3])
b=np.append(a,[4,5])
print(b)

[1 2 3 4 5]


In [88]:
c=np.array([[1,2],[3,4]])
d=np.append(c,[[10,20]],axis=0)
print(d)

[[ 1  2]
 [ 3  4]
 [10 20]]


In [92]:
a=np.array([1,2,3,4])
b=np.insert(a,2,[100,200])
print(b)

[  1   2 100 200   3   4]


In [100]:
a=np.array([1,2,3,4,5])
b=np.delete(a,[1,3])
print(b)
c=np.array([[1,2,3],[4,5,6]])
d=np.delete(c,1,axis=1)
print(d)

[1 3 5]
[[1 3]
 [4 6]]


In [106]:
a=np.array([1,2,3,4,5])
b=np.resize(a,(3,3,3))
print(b)

[[[1 2 3]
  [4 5 1]
  [2 3 4]]

 [[5 1 2]
  [3 4 5]
  [1 2 3]]

 [[4 5 1]
  [2 3 4]
  [5 1 2]]]
